window.translations = {
    uk: {
        page_title: "Головна",
        menu_about: "Про мене",
        menu_video: "Відео",
        menu_skill: "Навички",
        menu_quality: "Особисті якості",
        menu_project: "Мої проекти",
        hero_title: "Кирило Колчев <br> <span>Front-End Developer</span>",
        about_title: "Про мене",
        about_1: "Я — Front-End розробник, який захоплюється створенням сучасних, адаптивних і зручних для користувачів вебінтерфейсів. Мій шлях у веброзробці розпочався з базового розуміння HTML і CSS, але з часом я глибше занурився у світ JavaScript, React та інших сучасних технологій. Для мене важливо не просто написати код, а створити візуальний і функціональний досвід, який залишає приємне враження у користувача.",
        about_2: "Я активно використовую HTML5, CSS3, Sass, JavaScript (ES6+) та фреймворки, такі як React, щоб розробляти інтерфейси, які відповідають стандартам доступності й виглядають відмінно на будь-якому пристрої. Я розумію принципи адаптивної верстки, BEM-методологію, Git для контролю версій та інтегрую API для динамічного наповнення контенту.",
        about_3: "Крім того, я постійно вдосконалюю свої навички, слідкую за трендами в UI/UX та вивчаю нові інструменти, наприклад, TypeScript, Next.js або Tailwind CSS. Моєю метою є не просто технічна реалізація, а створення цифрового продукту, який буде корисним, естетичним і надійним.",
        about_4: "Я відкритий до нових проєктів, викликів і команд, де можу застосувати свої знання та внести цінність у спільну справу.",
        inform_title: "Відео",
        skill_title: "Навички",
        skill_1: "HTML, CSS, JS",
        skill_2: "Препроцесор ( SASS / SCSS)",
        skill_3: "Адаптивна верстка (чутливий дизайн)",
        skill_4: "Flexbox, Grid",
        skill_5: "Валідна верстка за стандартом W3C",
        skill_6: "Figma (дизайн-макети)",
        skill_7: "Методологія БЕМ",
        skill_8: "Інструменти розробки: Git, Webpack, npm,",
        quality_title: "Особисті якості",
        quality_1: "Стресостійкість та адаптивність",
        quality_2: "Здатність знаходити компромісні рішення у команді",
        quality_3: "Аналіз та виявлення потреб клієнтів, активне слухання",
        quality_4: "Критичне мислення та креативність",
        quality_5: "Ефективна командна робота",
        quality_6: "Постійне вдосконалення та навчання новим технологіям(дизайн-макети)",
        quality_7: "Гнучкість і вміння адаптуватися до нових задач",
        project_title: "Мої проекти"
    },
    en: {
        page_title: "Home",
        menu_about: "About Me",
        menu_video: "Video",
        menu_skill: "Skills",
        menu_quality: "Personal Qualities",
        menu_project: "My Projects",
        hero_title: "Kyrylo Kolchev <br> <span>Front-End Developer</span>",
        about_title: "About Me",
        about_1: "I am a Front-End developer passionate about creating modern, responsive, and user-friendly web interfaces. My journey in web development began with a basic understanding of HTML and CSS, but over time I delved deeper into the world of JavaScript, React, and other modern technologies. For me, it's important not just to write code, but to create a visual and functional experience that leaves a positive impression on the user.",
        about_2: "I actively use HTML5, CSS3, Sass, JavaScript (ES6+), and frameworks like React to develop interfaces that meet accessibility standards and look great on any device. I understand the principles of responsive design, the BEM methodology, use Git for version control, and integrate APIs for dynamic content.",
        about_3: "In addition, I am constantly improving my skills, following UI/UX trends, and learning new tools such as TypeScript, Next.js, or Tailwind CSS. My goal is not just technical implementation, but creating a digital product that is useful, aesthetic, and reliable.",
        about_4: "I am open to new projects, challenges, and teams where I can apply my knowledge and add value to a common cause.",
        inform_title: "Video",
        skill_title: "Skills",
        skill_1: "HTML, CSS, JS",
        skill_2: "Preprocessor (SASS / SCSS)",
        skill_3: "Responsive design (adaptive layout)",
        skill_4: "Flexbox, Grid",
        skill_5: "Valid layout according to W3C standard",
        skill_6: "Figma (design mockups)",
        skill_7: "BEM methodology",
        skill_8: "Development tools: Git, Webpack, npm,",
        quality_title: "Personal Qualities",
        quality_1: "Stress resistance and adaptability",
        quality_2: "Ability to find compromise solutions in a team",
        quality_3: "Analysis and identification of client needs, active listening",
        quality_4: "Critical thinking and creativity",
        quality_5: "Effective teamwork",
        quality_6: "Continuous improvement and learning of new technologies (design mockups)",
        quality_7: "Flexibility and ability to adapt to new tasks",
        project_title: "My Projects"
    }
};